---

- name: delete instance(s)
  gce:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
    instance_names: "{{ gce_prefix }}-{{ item.name }}"
    zone: "{{ gce_zone }}"
    state: absent
  async: 7200
  poll: 0
  register: deploy
  loop: "{{ nodes }}"
  when: nodes is defined

- pause:
    minutes: 2

- name: test instance completion
  async_status: jid="{{ item.ansible_job_id }}"
  register: instances
  loop: "{{ deploy.results }}"

- debug:
    var: instances

#- name: wait for instance deletion to complete
#  async_status: jid="{{ item.ansible_job_id }}"
#  register: instances
#  until: instances.finished
#  retries: "{{ instance_wait_retry_limit }}"
#  delay: 10
#  loop: "{{ deploy.results }}"