---

- name: delete instance(s)
  gce:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
    instance_names: "{{ gce_prefix }}-{{ item.name }}"
    zone: "{{ gce_zone }}"
    state: absent
  register: deploy
  loop: "{{ nodes }}"
  when: nodes is defined