---

- name: create instance(s)
  gce:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
    instance_names: "{{ gce_prefix }}-{{ item.name }}"
    zone: "{{ gce_zone }}"
    machine_type: "{{ item.machine_type }}"
    image: "{{ item.image }}"
    state: present
    metadata: '{"app_name":"{{ item.app_name }}", "role":"{{ item.role }}" }'
    tags:
      - app-name-{{ item.app_name | replace('_','-') }}
      - role-{{ item.role | replace('_','-') }}
      - "{{ item.network_tag | replace('_','-') }}"
  register: deploy
  loop: "{{ nodes }}"
  when: nodes is defined

- name: waiting for server to come online
  wait_for:
    host: "{{ item.instance_data.public_ip }}"
    port: "{{ ansible_port }}"
    timeout: "{{ instance_wait_connection_timeout }}"
  loop: "{{ deploy.results }}"
  when:
    - deploy.results is defined
    - nodes is defined
    - item.instance_data is defined
    - item.instance_data.public_ip is defined